weight=grand(10, 1, "uin", 1000, 6000)
disp("weight",weight)
performance=grand(10, 1, "uin", 6, 15)
disp('Performance',performance)
c=cov(weight,performance)
r=correl(weight,performance)
disp('Covarience',c)
disp('Correlation',r)
